ImageBoard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('apps.usuarios.urls')),
    url(r'',include('apps.board.urls')),
]

apps/board/urls.py
from . import views
from django.urls import path,include                                                                     
from django.conf.urls import url
from django.contrib.auth.decorators import login_required   
urlpatterns = [
    url(r'^$', views.index),
    url(r'^list/$',views.boardlist),
    path('<board>/',views.showboard,name='showboard'),
    path('<board>/new/',login_required(views.new_post),name='new_post'),
    path('<board>/<pk>/',views.post_detail,name='post_detail'),
]  

apps/usuarios/urls.py
from django.conf.urls import url
from apps.usuarios.views import RegistroUsuarios
from django.contrib.auth.views import login,logout                                                                                      
from django.contrib.auth.decorators import login_required   
from . import views
urlpatterns = [
    url(r'^register/$',RegistroUsuarios.as_view()),
    url(r'^login/$',login,{'template_name':'login.html'}),
    url(r'^logout/$', login_required(logout), {'next_page':'/'}),
    url(r'^profile/edit/$',login_required(views.update_profile),name='edit_profile'), 
    url(r'^profile/$',login_required(views.profile)), 
]

apps/board/models.py
from django.db import models
from django.utils import timezone
from storages.backends.ftp import FTPStorage
import hashlib
import os
fs = FTPStorage()
def update_filename(instance, filename):
    path = "img"
    fileName, fileExtension = os.path.splitext(filename)
    filename = filename+str(timezone.now())
    name = hashlib.sha256((filename).encode()).hexdigest()+fileExtension
    path  = os.path.join(path, name)
    return path
class Board(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=120)
    def __str__(self):
        return self.name
class Post(models.Model):
    board = models.ForeignKey('board.Board',on_delete=models.CASCADE, related_name='Board')
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=50)
    text = models.TextField()
    image = models.ImageField(upload_to=update_filename,storage=fs)
    def __str__(self):
        return self.title
class Comment(models.Model):
    post = models.ForeignKey('board.Post',on_delete=models.CASCADE,related_name = 'Post')
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to='static')
    def __str__(self):
        return self.text

apps/followers/models.py
from django.db import models
from django.contrib.auth.models import User
class Follower(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    followed = models.ForeignKey(User,on_delete=models.CASCADE,related_name = "followed_set")
    def __str__(self):
        return str(self.user)+" seguidor de "+str(self.followed)
# Create your models here.

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    userpic = models.ImageField(upload_to='img')  
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    def __str__(self):
        return self.user.username
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

apps/board/forms.py
from django import forms                                                                                                                                                    
from .models import Post
class PostForm(forms.ModelForm):                                                                                                                                            
    class Meta:                                                                                                                                                             
        model = Post                                                                                                                                                        
        fields = ('title', 'text', 'image')     

apps/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile
class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            ]
        labels = {
            'username':'Nickname',
            'email':'Correo',
            }
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('userpic','bio','location','birth_date')
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email') 

apps/board/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404, render,redirect
from .models import Board,Post
from apps.board.forms import PostForm  
# Create your views here.
def index(request):
    return render(request,'board/index.html',{})
def showboard(request,board):
    b = get_object_or_404(Board, name=board)
    posts = Post.objects.filter(board=b).order_by('-created_date')
    return render(request,'post/list.html',{'posts':posts,'board':b})
def post_detail(request,board,pk):
    b = get_object_or_404(Board, name=board)
    post = get_object_or_404(Post,pk=pk)
    return render(request,'post/detail.html',{'post':post,'board':b})

def boardlist(request):
    boards = Board.objects.all()
    return render(request,'boards.html',{'boards':boards}) 
def new_post(request,board):
    b = get_object_or_404(Board, name=board)
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.board = b
            post.save()
            return redirect("/"+board+"/")
    else:
        form = PostForm()
    return render(request,'post/new_post.html',{'form':form,'board':b})

apps/followers/views.py
from django.shortcuts import render

# Create your views here.

apps/usuarios/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from apps.usuarios.forms import RegistroForm,UserForm,ProfileForm
from django.shortcuts import render,redirect
class RegistroUsuarios(CreateView):
    model = User
    template_name = "usuarios/registrar.html"
    form_class = RegistroForm
    @property
    def success_url(self):
        return '/'
def profile(request):
    return render(request,'profile.html',{})
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST,request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            if 'userpic' in request.FILES:
                print("Foto!")
                p = profile_form.save(commit=False)
                p.picture = request.FILES['userpic']
                p.save()
            user_form.save()
            profile_form.save()
            return redirect('/profile/')
        else:print("NO se pudo guardar")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/editprofile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })
# Create your views here.

apps/board/templates/board/index.html
{% load staticfiles %}
<html lang="en">
<head>
  <title>0/0 Board!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Caveat+Brush|Press+Start+2P" rel="stylesheet" type="text/css">  
</head>
<body class="text-center aqua-gradient">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">0/0 Board</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="#">Iniciar</a>
            <a class="nav-link" href="#">Blog</a>
            <a class="nav-link" href="#">Contacto</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Carga, sube y comparte tus imagenes!</h1>
        <p class="lead">0/0 Board es una pagina en la cual podras subir tus imagenes y discutir sobre ellas, puedes compartir tantas imagenes que quieras! Hay varios hilos en los que podras interactuar con distintas personas!</p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-secondary">Leer mas</a>
        </p>
      </main>
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Desarrollado por <a href="https://t.me/JackCloudman">@JackCloudman</a></p>
        </div>
      </footer>
    </div>
</body>
</html>

templates/board/base.html
{% load staticfiles %}
<html>
<head>
  <title>0/0 Board!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Caveat+Brush|Press+Start+2P" rel="stylesheet" type="text/css">  
</head>
<body class="text-center">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    {% block content %}
    {% endblock %}
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Desarrollado por <a href="https://t.me/JackCloudman">@JackCloudman</a></p>
        </div>
      </footer>
    </div>
</body>
</html>

templates/board/index.html
{% extends 'board/base.html'%}
{% block content %}   
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">0/0 Board</h3>
    <nav class="nav nav-masthead justify-content-center">
    {% if user.is_authenticated %}
    <a class="nav-link" href="/logout/">{{ user.username }} Logout</a>
    {% else %}
    <a class="nav-link" href="/register/">Registrar</a>
     {% endif %} 
      <a class="nav-link" href="http://blog.jackcloudman.me/">Blog</a>
      <a class="nav-link" href="https://t.me/jackcloudman">Contacto</a>
    </nav>
  </div>
</header>
<main role="main" class="inner cover">
  <h1 class="cover-heading">Captura, sube y comparte todas tus fotos!</h1>
   <p class="lead">0/0 Board es una pagina en la cual podras subir tus imagenes y discutir sobre ellas, puedes compartir tantas imagenes que quieras! Hay varios hilos en los que podras interactuar con distintas personas!</p>
    <p class="lead">
    {% if user.is_authenticated %}
       <a href="/profile/" class="btn btn-lg btn-secondary">Ver Perfil</a>
    {% else %}
      <a href="/login/" class="btn btn-lg btn-secondary">Iniciar Sesion</a>
    {% endif %}</p> 
    <p class="lead">    
      <a href="/list/" class="btn btn-lg btn-secondary">Listado</a></p>
 </main>
{% endblock %}

templates/boards.html
{% extends 'post/base.html' %}                                                                                                                                          
{% block content %}
      <div class="jumbotron">                                                                                                                                               
         <h3 class="media-heading">A continuacion se muestran la lista de boards disponibles en la pagina:</h3>                                                                 </div>  
<div class="post">
    <ul>
    {%for board in boards%}
    <li><a href="/{{board.name}}/"><p>{{board.name}}: {{board.description}}</p><a></li>
    {% endfor %}
    </ul>
</div>
{%endblock%}

templates/login.html
{% extends 'usuarios/base.html' %}
 {% block content %}
 <header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><a href="/">0/0 Board</a></h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link" href="/register/">Registrar</a>
      <a class="nav-link" href="http://blog.jackcloudman.me/">Blog</a>
      <a class="nav-link" href="https://t.me/JackCloudman">Contacto</a>
    </nav>
  </div>
</header>
<form method="post">
    {% csrf_token %}
     <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Nombre de usuario:</label>
                <input class="form-control" type="text" name="username">
           </div>
        </div>
    </div>    
    <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Contraseña:</label>
                <input class="form-control" type="password" name="password">
           </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <a href="/">Olvidé mi contraseña</a>
                <input class="btn btn-primary" type="submit" value="Ingresar">
           </div>
        </div>
    </div>
{% if form.non_field_errors %}
    <ul class='form-errors'>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}
</form>
{% endblock %}

templates/post/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {%if post%}
        <title>/{{board.name}}/ - {{ post.title }}</title>
    {%else%}
        <title>/{{board.name}}/</title>
    {%endif%}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto+Mono|Francois+One" rel="stylesheet">
    <link href="{% static 'css/board.css' %}" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link" href="/">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/list/">Lista</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://blog.jackcloudman.me/">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://t.me/JackCloudman">Contacto</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">0/0 Board</h3>
      </div>
    {%block content%}
    {%endblock%}
    </div>
  </body>
</html

templates/post/detail.html
{% extends 'post/base.html' %}
{% block content %}
      <div class="jumbotron">
         <h3 class="media-heading"><i class="material-icons">collections</i> {{board.description}}</h3>
          <p class="lead">
    <a class="btn btn-primary btn-lg" href="/{{board.name}}/" role="button">Volver al board!</a>
  </p>
      </div>
        <div class="post">
            <div class="date">
            Publicado por {{post.author}}, {{ post.created_date }}
            </div>
            <h1><a>{{ post.title }}</a></h1>
            <div class="row">
            <div class="col-md-auto">
                 <div class="figure"><img class="rounded" src="http://storage.jackcloudman.me/{{post.image}}" onclick="expandir(this)" style="width:250px;margin-bottom:5px;"> </div>
            </div>
          <div class="col-md-7">
            <div>
                <p>{{post.text|linebreaksbr}}</p>
            </div>
              </div></div>
        </div>
        <hr>
<script type="text/javascript">
    function expandir(img){
        if(img.style.width=="100%"){
            img.style.width = "250px";
        }
        else{
            img.style.width = "100%";
        }
    }
</script>
{% endblock %}

templates/post/list.html
{% extends 'post/base.html' %}
{% block content %}
      <div class="jumbotron">
         <h3 class="media-heading"><i class="material-icons">collections</i> {{board.description}}</h3>
          <p class="lead">
    <a class="btn btn-primary btn-lg" href="new/" role="button">Añadir Post!</a>
  </p>
      </div>
    {% for post in posts %}
        <div class="post">
            <div class="date">
            Publicado por {{post.author}}, {{ post.created_date }}
            </div>
            <h1><a href="{{post.id}}/">{{ post.title }}</a></h1>
            <div class="row">
                <div class="col-md-auto">
                <div class="figure"><img class="rounded" src="http://storage.jackcloudman.me/{{post.image}}" onclick="expandir(this)" style="width:250px;margin-bottom:5px;"></div>
                </div>
                <div class="col-md-6">
                    <div>
                    <p>{{post.text|linebreaksbr}}</p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    {% endfor %}
<script type="text/javascript">
    function expandir(img){
        if(img.style.width=="100%"){
            img.style.width = "250px";
        }
        else{
            img.style.width = "100%";
        }
    }
</script>
{% endblock %}

templates/post/new_post.html
{% extends 'post/base.html' %}
{% block content %}
      <div class="jumbotron">
         <h3 class="media-heading">Añade un post a /{{board.name}}/</h3>
          <p class="lead">
    <a class="btn btn-primary btn-lg" href="/{{board.name}}/" role="button">Volver al Board!</a>
  </p></div>
<div class="post">
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <label for="id_title">Titulo:</label>
            <input class="form-control" type="text" id="id_title" name="title">
            </div>
        </div>
    </div>
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <label for="id_text">Texto:</label>
            <textarea class="form-control" id="id_text" name="text"></textarea>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <input class="form-control" type="file" id="id_image" name="image">
            </div>
        </div>
    </div>
<div class="form-group">
                <button class="btn btn-primary "type="submit">Guardar</button>
            </div>
</form>
</div>
{% endblock %}

templates/profile.html
{% extends 'usuarios/base.html' %}
 {% block content %}
 <header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><a href="/">0/0 Board</a></h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link" href="/logout/">{{ user.username }} Logout</a>
      <a class="nav-link" href="http://blog.jackcloudman.me">Blog</a>
      <a class="nav-link" href="https://t.me/JackCloudman">Contacto</a>
    </nav>
  </div>
</header>
<div style="margin-bottom:20px">
      <a href="/{{user.profile.userpic}}">
        <img src="/{{user.profile.userpic}}" alt="Si lees esto, puedes intentar cambiando tu imagen de usuario!" style="width:50%" class="rounded mx-auto d-block">
      </a>
    </div>
<ul>

  <li>Nombre: {{ user.first_name }}</li>
  <li>Apellidos: {{ user.last_name }}</li>
  <li>Username: {{ user.username }}</li>
  <li>Biografia: {{ user.profile.bio }}</li>
  <li>Localizacion: {{ user.profile.location }}</li>
  <li>Cumpleaños: {{ user.profile.birth_date }}</li>

</ul>
<main role="main" class="inner cover">                                                                                                  
    <p class="lead">                                                                                                                    
       <a href="edit/" class="btn btn-lg btn-secondary">Editar Perfil</a></p>                                                              
 </main> 
{% endblock %}

templates/profile2.html
{% extends 'usuarios/base.html' %}
 {% block content %}
 <header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><a href="/">0/0 Board</a></h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link" href="/logout/">{{ user.username }} Logout</a>
      <a class="nav-link" href="http://blog.jackcloudman.me">Blog</a>
      <a class="nav-link" href="https://t.me/JackCloudman">Contacto</a>
    </nav>
  </div>
</header>
<div class="container">
    <div id="myModal" tabindex="1"aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <center>
                    <img src="http://10.0.0.6/img/2015-07-18-752369_skn0Lfs.png" name="aboutme" width="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading">Joe Sixpack</h3><h4> <span class="glyphicon glyphicon-map-marker"></span><small>USA</small></h4>
                    <span><strong>Skills: </strong></span>
                        <span class="label label-warning">HTML5/CSS</span>
                        <span class="label label-info">Adobe CS 5.5</span>
                        <span class="label label-info">Microsoft Office</span>
                        <span class="label label-success">Windows XP, Vista, 7</span>
                    </center>
                    <hr>
                    <center>
                    <p class="text-left"><strong>Bio: </strong><br>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem dui, tempor sit amet commodo a, vulputate vel tellus.</p>
                    <br>
                    </center>
                </div>
                <div class="modal-footer">
                    <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal">I've heard enough about Joe</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>
<main role="main" class="inner cover">                                                                                                  
    <p class="lead">                                                                                                                    
       <a href="edit/" class="btn btn-lg btn-secondary">Editar Perfil</a></p>                                                              
 </main> 
{% endblock %}

templates/profiles/editprofile.html
{% extends 'usuarios/base.html'%}                                                                                                          
{% block content %}  
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    {%for field in user_form %}
      <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
            {{field.label_tag}}
            <input class="form-control" type="text" id="{{field.id_for_label}} " name="{{field.html_name}}" value="{{field.value}} ">
            </div>
        </div>
    </div>
    {%endfor%}
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <label for="id_location">Biografia:</label>
            <input class="form-control" type="text" id="id_bio" name="bio" value="{{profile_form.bio.value}} ">
            </div>
        </div>
    </div>
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <label for="id_location">Localizacion:</label>
            <input class="form-control" type="text" id="id_location" name="location" value="{{profile_form.location.value}} ">
            </div>
        </div>
    </div>
    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            <label for="id_location">Cumpleaños:</label>
            <input class="form-control" type="date" id="id_birth_date" name="birth_date" value="{{profile_form.birth_date.value}} ">
            </div>
        </div>
    </div>

    <div class="row justify-content-center">                                                                                          
        <div class="col-md-8 col-md-offset-2">                                                                                          
            <div class="form-group">
            {{profile_form.userpic.label}}
            <input class="form-control" type="file" id="id_userpic" name="userpic">
            </div>
        </div>
    </div>
<div class="form-group">
                <button class="btn btn-primary "type="submit">Guardar</button>
            </div>
</form>
{% endblock %}

templates/usuarios/base.html
{% load staticfiles %}
<html>
<head>
  <title>0/0 Board!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Caveat+Brush|Press+Start+2P" rel="stylesheet" type="text/css">  
</head>
<body class="text-center">
    <div class="cover-container d-flex h-400 p-3 mx-auto flex-column">
    {% block content %}
    {% endblock %}
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Desarrollado por <a href="https://t.me/JackCloudman">@JackCloudman</a> ,para mas informacion consulta el apartado de Blog.</p>
        </div>
      </footer>
    </div>
</body>
</html>